spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/postgres
    username: postgres
    password: terrrr
  jpa:
    show_sql: true
    format_sql: true
    hibernate:
      ddl-auto: update